name: Packer

on:
  - push

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"
      - name: Run `packer init`
        id: init
        run: "packer init /packer/packer-test.pkr.hcl"
      - name: Run `packer validate`
        id: validate
        run: "packer validate /packer/packer-test.pkr.hcl"

      - name: Build Artifact
        run: packer build -color=false -on-error=abort /packer/packer-test.pkr.hcl
        env:
          # HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          # HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          # HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2